/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Workstation
 */
public class frmIniciar extends javax.swing.JFrame {

    String usuario = "";
    String clave = "";

    static int disparador;

    /**
     * Creates new form frmIniciar
     */
    public frmIniciar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesPanel = new javax.swing.JPanel();
        usuarioLabel = new javax.swing.JLabel();
        claveLabel = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnRegistroUsuario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BBQ Party Restaurant");
        setResizable(false);

        opcionesPanel.setBackground(new java.awt.Color(255, 255, 255));
        opcionesPanel.setForeground(new java.awt.Color(52, 52, 52));
        opcionesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(0, 0, 0));
        usuarioLabel.setText("Usuario");
        opcionesPanel.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 59, 106, -1));

        claveLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        claveLabel.setForeground(new java.awt.Color(0, 0, 0));
        claveLabel.setText("Clave");
        opcionesPanel.add(claveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 143, 106, -1));
        opcionesPanel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 53, 143, 33));

        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClaveKeyPressed(evt);
            }
        });
        opcionesPanel.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 137, 143, 33));

        btnIngresar.setBackground(new java.awt.Color(102, 204, 153));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        opcionesPanel.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 235, 109, -1));

        btnSalir.setBackground(new java.awt.Color(226, 106, 106));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        opcionesPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 235, 109, -1));

        btnRegistroUsuario.setLabel("Ingresar como Cliente");
        btnRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUsuarioActionPerformed(evt);
            }
        });
        opcionesPanel.add(btnRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 299, 261, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/bannerflorwers.png"))); // NOI18N
        opcionesPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 280, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/bannerflorwers.png"))); // NOI18N
        opcionesPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 260, 60));

        logoPanel.setBackground(new java.awt.Color(255, 255, 255));
        logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/diet.png"))); // NOI18N
        logoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/shop.png"))); // NOI18N
        logoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/bannerflorwers.png"))); // NOI18N
        logoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 180, 160));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/sanblas (1121).png"))); // NOI18N
        logoPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 46, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/bannerflorwers.png"))); // NOI18N
        logoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 206, Short.MAX_VALUE)
                .addComponent(opcionesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 405, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        //CONDICION PARA ENTRAR COMO ADMINISTRADOR
        if (txtUsuario.getText().equals("admin") && txtUsuario.getText().equals("admin")) {
            this.dispose();
            frmMenuAdm menuAdm = new frmMenuAdm();
            menuAdm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "El USUARIO y/o CLAVE son INCORRECTOS");
            txtUsuario.setText("");
            txtClave.setText("");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_btnSalirActionPerformed
    
 
    private void btnRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUsuarioActionPerformed
        // TODO add your handling code here:
        frmListaMesasCliente mesasClientes = new frmListaMesasCliente();
        mesasClientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroUsuarioActionPerformed

    //metodo para inciar seccion con la tecla enter
    private void txtClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtUsuario.getText().equals("admin") && txtUsuario.getText().equals("admin")) {
                this.dispose();
                frmMenuAdm menuAdm = new frmMenuAdm();
                menuAdm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "El USUARIO y/o CLAVE son INCORRECTOS");
                txtUsuario.setText("");
                txtClave.setText("");
            }
        }

    }//GEN-LAST:event_txtClaveKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmIniciar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistroUsuario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel claveLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel opcionesPanel;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
